version: '3.8'

services:

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requierements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: ./requierements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    expose: 
      - "9000"
    # tty: true

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requierements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped 
    expose:
      - "3306"
    #tty: true
    # health_check: 
    


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kali/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kali/data/mariadb'

networks:
  inception:
    driver: bridge